name: Release Charts

# See https://github.com/helm/chart-releaser-action

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!charts/**/README.md'
  # For manual dispatch
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write # need to write a commit to the repo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ github.token }}"
        with:
          config: .github/cr.yaml
          mark_as_latest: false # only headlamp is set to latest
