name: Trigger Flatpak Headlamp version update

# See https://github.com/flathub/io.kinvolk.Headlamp
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger_flatpak_update:
    name: Trigger Flatpak Headlamp version update
    runs-on: ubuntu-latest

    permissions:
      secrets: read # needed to fetch gh token

    steps:
      - name: Trigger via gh
        env:
          GITHUB_TOKEN: ${{ secrets.FLATPAK_HEADLAMP_REPO_TOKEN }}
        run: |
          gh api repos/flathub/io.kinvolk.Headlamp/dispatches --raw-field event_type=headlamp-release
